# Generated by Django 3.2.3 on 2021-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256, unique=True)),
                ('link', models.TextField(max_length=256, unique=True)),
                ('icon', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256, unique=True)),
                ('link', models.TextField(max_length=256, unique=True)),
                ('icon', models.TextField(max_length=256)),
            ],
        ),
    ]
