# Generated by Django 3.2.3 on 2021-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShowElements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='icon2',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
